### ISSUE TITLE
(#GU5) Issue on Shell Challenge - Rust

### ISSUE THREAD

**Issue by vantdev** [codecrafters-io/docs#69]
On stage #GU5 - test for Stage #YT5 (Quoting - Backslash outside quotes) passes $ echo "before\    after"

This test fails every time because it is passed inside of quotes, therefore handled accordingly. Is there a reason this isn't being passed as $ echo before\    after? Am I missing something here in the intent?

remote: [tester::#YT5] Running tests for Stage #YT5 (Quoting - Backslash outside quotes)
remote: [tester::#YT5] Running ./your_program.sh
remote: [your-program] $ echo "before\   after"
remote: [your-program] before   after
remote: [tester::#YT5] Output does not match expected value.
remote: [tester::#YT5] Expected: "before\   after"
remote: [tester::#YT5] Received: "before   after"

**Comment by rohitpaulk** [comment]
Screenshots from zsh: 

<img width="177" alt="Screenshot 2024-12-20 at 12 39 47" src="https://github.com/user-attachments/assets/7290735e-aef0-49a1-9275-652fdf32763f" />

And from bash:

<img width="430" alt="Screenshot 2024-12-20 at 12 40 00" src="https://github.com/user-attachments/assets/d162d82a-88e8-4c94-a5ad-bb97b7c0a5f3" />

@vantdev seems like this is expected behaviour?

**Comment by rohitpaulk** [comment]
Closing until we have more proof that the tester behaviour is incorrect
